//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlashUSB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlashUSB.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Aktiver {
            get {
                return ResourceManager.GetString("Aktiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus type error. Expected USB.
        /// </summary>
        internal static string BusTypeNotUSB_Exception {
            get {
                return ResourceManager.GetString("BusTypeNotUSB_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate hub.
        /// </summary>
        internal static string ButtonTextActivate {
            get {
                return ResourceManager.GetString("ButtonTextActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate hub.
        /// </summary>
        internal static string ButtonTextDeactivate {
            get {
                return ResourceManager.GetString("ButtonTextDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean failed.
        /// </summary>
        internal static string CleanFailed {
            get {
                return ResourceManager.GetString("CleanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean error:.
        /// </summary>
        internal static string CleanFailedColon {
            get {
                return ResourceManager.GetString("CleanFailedColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        internal static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string Deaktiver {
            get {
                return ResourceManager.GetString("Deaktiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk type error. Expected removable.
        /// </summary>
        internal static string DriveNotRemovableException {
            get {
                return ResourceManager.GetString("DriveNotRemovableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        internal static string EB {
            get {
                return ResourceManager.GetString("EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string ErrorColon {
            get {
                return ResourceManager.GetString("ErrorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format failed.
        /// </summary>
        internal static string FormatFailed {
            get {
                return ResourceManager.GetString("FormatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All memory sticks inserted in hub {0}, will be initialized as specified.
        /// </summary>
        internal static string MsgBoxOnActivateText {
            get {
                return ResourceManager.GetString("MsgBoxOnActivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUB activated.
        /// </summary>
        internal static string MsgBoxOnActivateTextCaption {
            get {
                return ResourceManager.GetString("MsgBoxOnActivateTextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK - ejecting.
        /// </summary>
        internal static string OK_Eject {
            get {
                return ResourceManager.GetString("OK_Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        internal static string PB {
            get {
                return ResourceManager.GetString("PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string PreVersion {
            get {
                return ResourceManager.GetString("PreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YB.
        /// </summary>
        internal static string YB {
            get {
                return ResourceManager.GetString("YB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZB.
        /// </summary>
        internal static string ZB {
            get {
                return ResourceManager.GetString("ZB", resourceCulture);
            }
        }
    }
}
